'use strict';
/**
 * Revoke keys generated by the broken Linkvertise direct-complete bypass flow.
 * Run: node scripts/revoke_broken_lv_keys.js
 *
 * Requires SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY to be set in environment.
 * Source the .env file first:  set -a && source site/.env && set +a
 * Or on Windows: use dotenv or export the vars in the shell before running.
 *
 * Keys to revoke (from live/user test of the broken flow):
 *   DENG-2B17-4DE8-17D2-7EF2
 *   DENG-2095-6BB3-9D05-9EA4  (revoke only if confirmed test-flow key)
 */
const { createClient } = require('@supabase/supabase-js');
const crypto = require('crypto');

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
  console.error('[revoke] ERROR: SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY must be set.');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

// Known broken-flow test keys. SHA-256 of the raw key is stored as license_keys.id.
const BROKEN_KEYS = [
  'DENG-2B17-4DE8-17D2-7EF2',
  // Uncomment below only if confirmed to be from broken test flow:
  // 'DENG-2095-6BB3-9D05-9EA4',
];

function sha256Key(rawKey) {
  return crypto.createHash('sha256').update(rawKey).digest('hex');
}

async function main() {
  for (const rawKey of BROKEN_KEYS) {
    const keyId = sha256Key(rawKey);
    console.log('[revoke] checking key_id=%s (raw=%s)', keyId.slice(0, 16) + '...', rawKey.slice(0, 9) + '****');

    // 1. Look up the challenge row to confirm it came from the broken flow
    const { data: challenges, error: cErr } = await supabase
      .from('license_ad_challenges')
      .select('id, site_user_id, provider, status, provider_payload, created_at')
      .eq('license_key_id', keyId);

    if (cErr) {
      console.error('[revoke] challenge lookup error:', cErr.message);
      continue;
    }
    if (!challenges || challenges.length === 0) {
      console.log('[revoke] no challenge row found for this key — skipping (key may not exist)');
      continue;
    }

    const ch = challenges[0];
    const payload = ch.provider_payload || {};

    // Safety check: confirm it's a linkvertise key from the broken period
    if (ch.provider !== 'linkvertise') {
      console.log('[revoke] challenge provider=%s — not a Linkvertise key, skipping', ch.provider);
      continue;
    }

    console.log('[revoke] found challenge id=%s provider=%s status=%s created_at=%s',
      ch.id, ch.provider, ch.status, ch.created_at);
    console.log('[revoke] provider_payload.redirect_started=%s provider_started_at=%s',
      payload.redirect_started, payload.provider_started_at);

    // 2. Mark the license key as revoked
    const { error: keyErr } = await supabase
      .from('license_keys')
      .update({ status: 'revoked' })
      .eq('id', keyId);

    if (keyErr) {
      console.error('[revoke] license_keys update error:', keyErr.message);
    } else {
      console.log('[revoke] license_keys.status -> revoked for key_id prefix=%s', keyId.slice(0, 16));
    }

    // 3. Mark the challenge as failed with audit note
    const { error: chErr } = await supabase
      .from('license_ad_challenges')
      .update({
        status: 'failed',
        failure_reason: 'revoked broken Linkvertise direct-complete test key',
      })
      .eq('id', ch.id);

    if (chErr) {
      console.error('[revoke] license_ad_challenges update error:', chErr.message);
    } else {
      console.log('[revoke] challenge id=%s -> failed (revoked broken test key)', ch.id);
    }
  }
  console.log('[revoke] done');
}

main().catch((err) => {
  console.error('[revoke] fatal:', err.message || err);
  process.exit(1);
});
